version: 1
subgraphs:
  # - name: 
  #   routing_url: http://localhost:3003/graphql
  #   # a) Specify a schema to introspect by file OR
  #   schema:
  #     file: ../schemas/subgraph-a.graphqls
  # b) Specify introspection to introspect on a running subgraph
  #   introspection:
  #     url: http://localhost:3003/postsandauthors
  #   headers:
  #     Authorization: 'Bearer YOUR_TOKEN_HERE'
  - name: postsandauthors
    routing_url: http://localhost:3003/postsandauthors
    introspection:
      url: http://localhost:3003/postsandauthors
  - name: images
    routing_url: http://localhost:3004/images
    introspection:
      url: http://localhost:3004/images
  - name: tags
    routing_url: http://localhost:3005/tags
    introspection:
      url: http://localhost:3005/tags